-- ============================================
-- NATIONAL HELPLINES TABLE
-- ============================================
-- This SQL creates a table to store national emergency helpline numbers
-- Run this in your Supabase SQL Editor

-- Create the national_helplines table
CREATE TABLE IF NOT EXISTS national_helplines (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title VARCHAR(255) NOT NULL,
  phone_number VARCHAR(50) NOT NULL,
  description TEXT,
  display_order INTEGER DEFAULT 0,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);


-- ============================================
-- INSERT NATIONAL EMERGENCY HELPLINES
-- ============================================

INSERT INTO national_helplines (title, phone_number, description, display_order) VALUES
('Police', '112', 'Emergency Police Helpline for immediate assistance', 1),
('Ambulance', '108', 'Emergency Ambulance Service for medical assistance', 2),
('Fire', '101', 'Fire Emergency Helpline', 3),
('National Helpline', '14567', 'National Emergency Helpline for all emergencies', 4);

-- ============================================
-- VERIFY DATA
-- ============================================

-- Display all inserted national helplines
SELECT
  title,
  phone_number,
  description,
  display_order,
  is_active
FROM national_helplines
ORDER BY display_order;

-- Count total helplines
SELECT
  COUNT(*) as total_helplines
FROM national_helplines
WHERE is_active = true;

-- ============================================
-- QUERIES FOR FLUTTER APP
-- ============================================

-- Query to get all active national helplines
-- SELECT * FROM national_helplines
-- WHERE is_active = true
-- ORDER BY display_order;
